apiVersion: v1
kind: ConfigMap
metadata:
  name: cm-processing
data:
  AWS_REGION: us-east-1
  AWS_S3_BUCKET: hack-video-processing-bucket
  AWS_S3_BUCKET_ZIP: hack-processed-zip-bucket
  VIDEO_PROCESSING_INPUT_QUEUE: https://sqs.us-east-1.amazonaws.com/619104548756/video-processing-input-queue
  VIDEO_PROCESSED_OUTPUT_QUEUE: https://sqs.us-east-1.amazonaws.com/619104548756/video-processed-output-queue