apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-video-processing
  labels:
    app: hack-video-processing
spec:
  selector:
    matchLabels:
      app: hack-video-processing
  template:
    metadata:
      labels:
        app: hack-video-processing
    spec:
      containers:
      - name: hack-video-processing
        image: thiagoluis88/hack-video-processing:1.0.6
        # volumeMounts:
        # - name: secrets-store-inline
        #   mountPath: "/mnt/secrets-store"
        #   readOnly: true
        envFrom:
          - secretRef:
              name: app-env-secret
          - configMapRef:
              name: cm-processing
        ports:
        - containerPort: 3211
          # name: app
        # - containerPort: 3211
        #   name: redoc
        livenessProbe:
          httpGet:
            path: /health
            port: 3211
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3211
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "aws-secrets"
