apiVersion: v1
kind: Service
metadata:
  name: svc-video-uploader
  labels:
    kubernetes.io/service-name: svc-video-uploader
  annotations:
    service.beta.kubernetes.io/aws-load-balancer-internal: "true"
    service.beta.kubernetes.io/aws-load-balancer-type: "nlb"
    service.beta.kubernetes.io/aws-load-balancer-nlb-target-type: ip
spec:
  type: LoadBalancer
  ports:
    - port: 80
      protocol: TCP
      targetPort: 3210
  selector:
    app: hack-uploader

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: hack-uploader
  labels:
    app: hack-uploader
spec:
  selector:
    matchLabels:
      app: hack-uploader
  template:
    metadata:
      labels:
        app: hack-uploader
    spec:
      containers:
      - name: hack-uploader
        image: thiagoluis88/hack-video-uploader:1.0.10
        # volumeMounts:
        # - name: secrets-store-inline
        #   mountPath: "/mnt/secrets-store"
        #   readOnly: true
        envFrom:
          - secretRef:
              name: app-env-secret
          - configMapRef:
              name: cm-uploader
        ports:
        - containerPort: 3210
          # name: app
        # - containerPort: 3211
        #   name: redoc
        livenessProbe:
          httpGet:
            path: /health
            port: 3210
          periodSeconds: 10
          failureThreshold: 3
          initialDelaySeconds: 15
        readinessProbe:
          httpGet:
            path: /health
            port: 3210
          periodSeconds: 10
          failureThreshold: 5
          successThreshold: 1
          initialDelaySeconds: 3
        resources:
          requests:
            cpu: 50m
      # volumes:
      #   - name: secrets-store-inline
      #     csi:
      #       driver: secrets-store.csi.k8s.io
      #       readOnly: true
      #       volumeAttributes:
      #         secretProviderClass: "aws-secrets"
